{"level":"error","message":"Ошибка при регистрации пользователя:","service":"pa-auth-service","timestamp":"2025-01-18T16:19:06.727Z"}
{"code":409,"error":409,"level":"error","message":"Конфликт запроса с текущим состоянием сервера.","service":"pa-auth-service","timestamp":"2025-01-18T16:19:06.730Z"}
{"level":"error","message":"Ошибка при регистрации пользователя:","service":"pa-auth-service","timestamp":"2025-01-18T16:21:41.885Z"}
{"code":409,"error":409,"level":"error","message":"Конфликт запроса с текущим состоянием сервера.","service":"pa-auth-service","timestamp":"2025-01-18T16:21:41.888Z"}
{"level":"error","message":"Ошибка при регистрации пользователя:","service":"pa-auth-service","timestamp":"2025-01-18T16:21:43.489Z"}
{"code":409,"error":409,"level":"error","message":"Конфликт запроса с текущим состоянием сервера.","service":"pa-auth-service","timestamp":"2025-01-18T16:21:43.492Z"}
{"code":409,"isOperational":true,"level":"error","message":"Такой пользователь уже существует.","service":"pa-auth-service","stack":"Error: Такой пользователь уже существует.\n    at exports.register (C:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:36:29)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","timestamp":"2025-01-18T16:45:28.860Z"}
{"code":409,"isOperational":true,"level":"error","message":"Такой пользователь уже существует.","service":"pa-auth-service","stack":"Error: Такой пользователь уже существует.\n    at exports.register (C:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:36:29)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","timestamp":"2025-01-18T16:47:02.417Z"}
{"code":409,"isOperational":true,"level":"error","message":"Такой пользователь уже существует.","service":"pa-auth-service","stack":"Error: Такой пользователь уже существует.\n    at exports.register (C:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:36:29)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","timestamp":"2025-01-18T16:53:50.732Z"}
{"code":409,"isOperational":true,"level":"error","message":"Такой пользователь уже существует.","service":"pa-auth-service","stack":"Error: Такой пользователь уже существует.\n    at exports.register (C:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:36:29)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","timestamp":"2025-01-18T16:55:44.020Z"}
{"level":"error","message":"Must call super constructor in derived class before accessing 'this' or returning from derived constructor","service":"pa-auth-service","stack":"ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor\n    at new CustomError (C:\\Distrib\\TZ\\AuthService\\helpers\\CustomError.js:3:7)\n    at exports.register (C:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:36:29)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","timestamp":"2025-01-18T16:56:42.403Z"}
{"code":409,"isOperational":true,"level":"error","message":"Такой пользователь уже существует.","service":"pa-auth-service","stack":"Error: Такой пользователь уже существует.\n    at exports.register (C:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:36:29)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","timestamp":"2025-01-18T16:58:31.709Z"}
{"code":409,"isOperational":true,"level":"error","message":"Такой пользователь уже существует.","service":"pa-auth-service","stack":"Error: Такой пользователь уже существует.\n    at exports.register (C:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:36:29)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","timestamp":"2025-01-18T17:59:32.475Z"}
{"code":409,"isOperational":true,"level":"error","message":"Такой пользователь уже существует.","service":"pa-auth-service","stack":"Error: Такой пользователь уже существует.\n    at exports.register (C:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:34:29)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","timestamp":"2025-01-18T19:07:25.699Z"}
{"code":422,"isOperational":true,"level":"error","message":"Пользователь не найден","service":"pa-auth-service","stack":"Error: Пользователь не найден\n    at exports.login (C:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:63:22)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","timestamp":"2025-01-18T19:15:19.087Z"}
{"level":"error","message":"commonFunction is not defined","service":"pa-auth-service","stack":"ReferenceError: commonFunction is not defined\n    at exports.login (C:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:66:45)","timestamp":"2025-01-19T13:29:06.054Z"}
{"level":"error","message":"commonFunction is not defined","service":"pa-auth-service","stack":"ReferenceError: commonFunction is not defined\n    at exports.login (C:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:70:45)","timestamp":"2025-01-25T21:12:14.644Z"}
{"code":400,"isOperational":true,"level":"error","message":"Ошибка получения кода верификации","service":"pa-auth-service","stack":"Error: Ошибка получения кода верификации\n    at exports.checkVerificationCode (c:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:223:44)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","timestamp":"2025-01-27T17:44:40.798Z"}
{"code":400,"isOperational":true,"level":"error","message":"Ошибка получения кода верификации","service":"pa-auth-service","stack":"Error: Ошибка получения кода верификации\n    at exports.checkVerificationCode (c:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:223:44)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","timestamp":"2025-01-27T18:22:22.389Z"}
{"code":422,"isOperational":true,"level":"error","message":"Пользователь не найден","service":"pa-auth-service","stack":"Error: Пользователь не найден\n    at exports.login (c:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:67:22)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","timestamp":"2025-02-01T10:18:44.788Z"}
{"level":"error","message":"commonFunction is not defined","service":"pa-auth-service","stack":"ReferenceError: commonFunction is not defined\n    at exports.logout (c:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:183:35)\n    at Layer.handle [as handle_request] (c:\\Distrib\\TZ\\AuthService\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (c:\\Distrib\\TZ\\AuthService\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (c:\\Distrib\\TZ\\AuthService\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (c:\\Distrib\\TZ\\AuthService\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at c:\\Distrib\\TZ\\AuthService\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (c:\\Distrib\\TZ\\AuthService\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (c:\\Distrib\\TZ\\AuthService\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (c:\\Distrib\\TZ\\AuthService\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (c:\\Distrib\\TZ\\AuthService\\node_modules\\express\\lib\\router\\index.js:47:12)","timestamp":"2025-02-01T17:37:08.101Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-4078,"level":"error","message":"Ошибка выполнения SQL-запроса: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"service":"pa-auth-service","stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)","syscall":"connect","timestamp":"2025-02-16T06:19:27.096Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-4078,"level":"error","message":"Ошибка при поиске пользователя по email: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"service":"pa-auth-service","stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)","syscall":"connect","timestamp":"2025-02-16T06:19:27.107Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-4078,"level":"error","message":"connect ECONNREFUSED 127.0.0.1:5432","port":5432,"service":"pa-auth-service","stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)","syscall":"connect","timestamp":"2025-02-16T06:19:27.108Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-4078,"level":"error","message":"Ошибка выполнения SQL-запроса: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"service":"pa-auth-service","stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)","syscall":"connect","timestamp":"2025-02-16T06:19:37.884Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-4078,"level":"error","message":"Ошибка при поиске пользователя по email: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"service":"pa-auth-service","stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)","syscall":"connect","timestamp":"2025-02-16T06:19:37.887Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-4078,"level":"error","message":"connect ECONNREFUSED 127.0.0.1:5432","port":5432,"service":"pa-auth-service","stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)","syscall":"connect","timestamp":"2025-02-16T06:19:37.888Z"}
{"level":"error","message":"commonFunction is not defined","service":"pa-auth-service","stack":"ReferenceError: commonFunction is not defined\n    at exports.login (c:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:70:45)","timestamp":"2025-02-16T06:21:53.316Z"}
{"level":"error","message":"commonFunction is not defined","service":"pa-auth-service","stack":"ReferenceError: commonFunction is not defined\n    at exports.login (c:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:70:45)","timestamp":"2025-02-16T10:24:24.004Z"}
{"level":"error","message":"commonFunction is not defined","service":"pa-auth-service","stack":"ReferenceError: commonFunction is not defined\n    at exports.login (c:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:70:45)","timestamp":"2025-02-19T17:27:57.057Z"}
{"level":"error","message":"commonFunction is not defined","service":"pa-auth-service","stack":"ReferenceError: commonFunction is not defined\n    at exports.login (c:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:70:45)","timestamp":"2025-02-19T17:28:09.730Z"}
{"code":"42501","file":"aclchk.c","length":108,"level":"error","line":"2843","message":"Ошибка выполнения SQL-запроса: permission denied for schema pa_auth_service","name":"error","position":"15","routine":"aclcheck_error","service":"pa-auth-service","severity":"ERROR","stack":"error: permission denied for schema pa_auth_service\n    at Parser.parseErrorMessage (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\parser.js:283:98)\n    at Parser.handlePacket (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\parser.js:122:29)\n    at Parser.parse (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\parser.js:35:38)\n    at Socket.<anonymous> (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:131:14)","timestamp":"2025-02-23T10:46:30.292Z"}
{"code":"42501","file":"aclchk.c","length":108,"level":"error","line":"2843","message":"Ошибка при поиске пользователя по email: permission denied for schema pa_auth_service","name":"error","position":"15","routine":"aclcheck_error","service":"pa-auth-service","severity":"ERROR","stack":"error: permission denied for schema pa_auth_service\n    at Parser.parseErrorMessage (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\parser.js:283:98)\n    at Parser.handlePacket (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\parser.js:122:29)\n    at Parser.parse (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\parser.js:35:38)\n    at Socket.<anonymous> (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:131:14)","timestamp":"2025-02-23T10:46:30.303Z"}
{"code":"42501","file":"aclchk.c","length":108,"level":"error","line":"2843","message":"permission denied for schema pa_auth_service","name":"error","position":"15","routine":"aclcheck_error","service":"pa-auth-service","severity":"ERROR","stack":"error: permission denied for schema pa_auth_service\n    at Parser.parseErrorMessage (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\parser.js:283:98)\n    at Parser.handlePacket (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\parser.js:122:29)\n    at Parser.parse (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\parser.js:35:38)\n    at Socket.<anonymous> (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:131:14)","timestamp":"2025-02-23T10:46:30.306Z"}
{"code":"42501","file":"aclchk.c","length":108,"level":"error","line":"2843","message":"Ошибка выполнения SQL-запроса: permission denied for schema pa_auth_service","name":"error","position":"15","routine":"aclcheck_error","service":"pa-auth-service","severity":"ERROR","stack":"error: permission denied for schema pa_auth_service\n    at Parser.parseErrorMessage (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\parser.js:283:98)\n    at Parser.handlePacket (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\parser.js:122:29)\n    at Parser.parse (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\parser.js:35:38)\n    at Socket.<anonymous> (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:131:14)","timestamp":"2025-02-23T10:47:44.987Z"}
{"code":"42501","file":"aclchk.c","length":108,"level":"error","line":"2843","message":"Ошибка при поиске пользователя по email: permission denied for schema pa_auth_service","name":"error","position":"15","routine":"aclcheck_error","service":"pa-auth-service","severity":"ERROR","stack":"error: permission denied for schema pa_auth_service\n    at Parser.parseErrorMessage (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\parser.js:283:98)\n    at Parser.handlePacket (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\parser.js:122:29)\n    at Parser.parse (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\parser.js:35:38)\n    at Socket.<anonymous> (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:131:14)","timestamp":"2025-02-23T10:47:44.991Z"}
{"code":"42501","file":"aclchk.c","length":108,"level":"error","line":"2843","message":"permission denied for schema pa_auth_service","name":"error","position":"15","routine":"aclcheck_error","service":"pa-auth-service","severity":"ERROR","stack":"error: permission denied for schema pa_auth_service\n    at Parser.parseErrorMessage (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\parser.js:283:98)\n    at Parser.handlePacket (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\parser.js:122:29)\n    at Parser.parse (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\parser.js:35:38)\n    at Socket.<anonymous> (C:\\Distrib\\TZ\\AuthService\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:131:14)","timestamp":"2025-02-23T10:47:44.994Z"}
{"level":"error","message":"tokenFromHeader is not defined","service":"pa-auth-service","stack":"ReferenceError: tokenFromHeader is not defined\n    at exports.getMe (C:\\Distrib\\TZ\\AuthService\\controllers\\authController.js:124:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","timestamp":"2025-02-25T14:26:49.688Z"}
